export { getProductDetailsData } from './model/selectors/getProductDetailsData/getProductDetailsData'
export { getProductDetailsError } from './model/selectors/getProductDetailsError/getProductDetailsError'
export { getProductDetailsForm } from './model/selectors/getProductDetailsForm/getProductDetailsForm'
export { getProductDetailsIsLoading } from './model/selectors/getProductDetailsIsLoading/getProductDetailsIsLoading'

export {ProductList} from './ui/ProductList/ProductList'
export { addProduct } from './model/services/addProduct/addProduct'
export { deleteProduct } from './model/services/deleteProduct/deleteProduct'
export { fetchAllProducts } from './model/services/fetchAllProduct.ts/fetchAllProducts'
export { getProductById } from './model/services/getProductById/getProductById'
export { getProductsByCategory } from './model/services/getProductsByCategory/getProductsByCategory'
export { updateProduct } from './model/services/updateProduct/updateProduct'

export {ProductCard} from './ui/ProductCard/ProductCard'
export type {Product} from './model/types/Product'
export { ProductType} from './model/types/Product'
