export { eventDetailAction, eventDetailReducer } from './model/slice/EventDetailPageSlice'
export { getEventDetailData } from './model/selectors/getEventDetailData/getEventDetailData'
export { getEventDetailError } from './model/selectors/getEventDetailError/getEventDetailError'
export { getEventDetailIsLoading } from './model/selectors/getEventDetailIsLoading/getEventDetailIsLoading'
export { getEventDetailsEventTypes } from './model/selectors/getEventDetailsEventTypes/getEventDetailsEventTypes'
export { getEventDetailsForm } from './model/selectors/getEventDetailsForm/getEventDetailsForm'
export type { EventDetailPageSchema } from './model/types/EventDetailPage'
export {EventDetailPage} from './ui/EventDetailPage'