export { getProjectPageOrders } from './model/selectors/getProjectPageOrders/getProjectPageOrders'
export { getProjectPageData } from './model/selectors/getProjectPageData/getProjectPageData'
export { getProjectPageError } from './model/selectors/getProjectPageError/getProjectPageError'
export { getProjectPageIsLoading } from './model/selectors/getProjectPageIsLoading/getProjectPageIsLoading'
export { projectsPageAction, projectsPageReducer } from './model/slice/ProjectsPageSlice'
export { ProjectsPageSchema } from './model/types/ProjectsPage'
export {ProjectsPage} from './ui/ProjectsPage'