name: Linting, testing, building
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: cd client && npm install
      - name: build production project
        run: cd client && npm run build:prod
      - name: linting typescript
        run: cd client && npm run lint:ts
        if: always()
      - name: linting css
        run: cd client && npm run lint:scss
        if: always()
      - name: unit tests
        run: cd client && npm run test:unit
        if: always()
      - name: Publish to Chromatic
        run: cd client && npx chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        if: always()
        